DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS recycling CASCADE;
DROP TABLE IF EXISTS organics CASCADE;
DROP TABLE IF EXISTS garbage CASCADE;
DROP TABLE IF EXISTS user_waste CASCADE;

CREATE TABLE users (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  score INTEGER
);

CREATE TABLE recycling (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL
);

CREATE TABLE organics (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL
);

CREATE TABLE garbage (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL
);

CREATE TABLE user_waste (
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  recycling_id INTEGER UNIQUE REFERENCES recycling(id) ON DELETE CASCADE,
  organic_id INTEGER UNIQUE REFERENCES organics(id) ON DELETE CASCADE,
  garbage_id INTEGER UNIQUE REFERENCES garbage(id) ON DELETE CASCADE
);
